###
GET http://localhost:3001/api/persons

###
DELETE http://localhost:3001/api/persons/1

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Federico",
    "number": "123456"
}

###

POST http://localhost:3001/api/persons
content-type: application/json

{
    "number": "123456"
}
