###
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/66d04f5f9fa2a63942f90017

###
DELETE http://localhost:3001/api/persons/

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Federico",
    "number": "123456"
}

###

POST http://localhost:3001/api/persons
content-type: application/json

{
    "number": "123456"
}
